//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegionIndexData", Namespace="http://webservices.example.com/GameServices/Game1")]
    public partial class RegionIndexData : object
    {
        
        private System.Collections.Generic.List<ServiceReference.Region> RegionsField;
        
        private System.Collections.Generic.List<ServiceReference.District> DistrictsField;
        
        private System.Collections.Generic.List<ServiceReference.Settlement> SettlementsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<ServiceReference.Region> Regions
        {
            get
            {
                return this.RegionsField;
            }
            set
            {
                this.RegionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.Generic.List<ServiceReference.District> Districts
        {
            get
            {
                return this.DistrictsField;
            }
            set
            {
                this.DistrictsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.Generic.List<ServiceReference.Settlement> Settlements
        {
            get
            {
                return this.SettlementsField;
            }
            set
            {
                this.SettlementsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Region", Namespace="http://webservices.example.com/GameServices/Game1")]
    public partial class Region : object
    {
        
        private int IdField;
        
        private string NameField;
        
        private string CapitalField;
        
        private System.Collections.Generic.List<ServiceReference.District> DistrictsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Capital
        {
            get
            {
                return this.CapitalField;
            }
            set
            {
                this.CapitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.Generic.List<ServiceReference.District> Districts
        {
            get
            {
                return this.DistrictsField;
            }
            set
            {
                this.DistrictsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="District", Namespace="http://webservices.example.com/GameServices/Game1")]
    public partial class District : object
    {
        
        private int IdField;
        
        private string NameField;
        
        private int RegionIdField;
        
        private System.Collections.Generic.List<ServiceReference.Settlement> SettlementsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RegionId
        {
            get
            {
                return this.RegionIdField;
            }
            set
            {
                this.RegionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<ServiceReference.Settlement> Settlements
        {
            get
            {
                return this.SettlementsField;
            }
            set
            {
                this.SettlementsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Settlement", Namespace="http://webservices.example.com/GameServices/Game1")]
    public partial class Settlement : object
    {
        
        private int IdField;
        
        private string NameField;
        
        private string TypeField;
        
        private int PopulationField;
        
        private int DistrictIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Population
        {
            get
            {
                return this.PopulationField;
            }
            set
            {
                this.PopulationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int DistrictId
        {
            get
            {
                return this.DistrictIdField;
            }
            set
            {
                this.DistrictIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.example.com/GameServices/Game1", ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.example.com/GameServices/Game1/IndexAsync", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.IndexAsyncResponse> IndexAsyncAsync(ServiceReference.IndexAsyncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.example.com/GameServices/Game1/SIndex", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.SIndexResponse> SIndexAsync(ServiceReference.SIndexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.example.com/GameServices/Game1/Create", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.CreateResponse> CreateAsync(ServiceReference.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.example.com/GameServices/Game1/Edit", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.EditResponse> EditAsync(ServiceReference.EditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.example.com/GameServices/Game1/PostEdit", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.PostEditResponse> PostEditAsync(ServiceReference.PostEditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.example.com/GameServices/Game1/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.DeleteResponse> DeleteAsync(ServiceReference.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.example.com/GameServices/Game1/PostDelete", ReplyAction="*")]
        System.Threading.Tasks.Task PostDeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.example.com/GameServices/Game1/GetDistrictsList", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.GetDistrictsListResponse> GetDistrictsListAsync(ServiceReference.GetDistrictsListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IndexAsyncRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IndexAsync", Namespace="http://webservices.example.com/GameServices/Game1", Order=0)]
        public ServiceReference.IndexAsyncRequestBody Body;
        
        public IndexAsyncRequest()
        {
        }
        
        public IndexAsyncRequest(ServiceReference.IndexAsyncRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.example.com/GameServices/Game1")]
    public partial class IndexAsyncRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<int> id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<int> districtId;
        
        public IndexAsyncRequestBody()
        {
        }
        
        public IndexAsyncRequestBody(System.Nullable<int> id, System.Nullable<int> districtId)
        {
            this.id = id;
            this.districtId = districtId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IndexAsyncResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IndexAsyncResponse", Namespace="http://webservices.example.com/GameServices/Game1", Order=0)]
        public ServiceReference.IndexAsyncResponseBody Body;
        
        public IndexAsyncResponse()
        {
        }
        
        public IndexAsyncResponse(ServiceReference.IndexAsyncResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.example.com/GameServices/Game1")]
    public partial class IndexAsyncResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.RegionIndexData IndexAsyncResult;
        
        public IndexAsyncResponseBody()
        {
        }
        
        public IndexAsyncResponseBody(ServiceReference.RegionIndexData IndexAsyncResult)
        {
            this.IndexAsyncResult = IndexAsyncResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SIndexRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SIndex", Namespace="http://webservices.example.com/GameServices/Game1", Order=0)]
        public ServiceReference.SIndexRequestBody Body;
        
        public SIndexRequest()
        {
        }
        
        public SIndexRequest(ServiceReference.SIndexRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SIndexRequestBody
    {
        
        public SIndexRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SIndexResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SIndexResponse", Namespace="http://webservices.example.com/GameServices/Game1", Order=0)]
        public ServiceReference.SIndexResponseBody Body;
        
        public SIndexResponse()
        {
        }
        
        public SIndexResponse(ServiceReference.SIndexResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.example.com/GameServices/Game1")]
    public partial class SIndexResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReference.Settlement> SIndexResult;
        
        public SIndexResponseBody()
        {
        }
        
        public SIndexResponseBody(System.Collections.Generic.List<ServiceReference.Settlement> SIndexResult)
        {
            this.SIndexResult = SIndexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create", Namespace="http://webservices.example.com/GameServices/Game1", Order=0)]
        public ServiceReference.CreateRequestBody Body;
        
        public CreateRequest()
        {
        }
        
        public CreateRequest(ServiceReference.CreateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.example.com/GameServices/Game1")]
    public partial class CreateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.Settlement settlement;
        
        public CreateRequestBody()
        {
        }
        
        public CreateRequestBody(ServiceReference.Settlement settlement)
        {
            this.settlement = settlement;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateResponse", Namespace="http://webservices.example.com/GameServices/Game1", Order=0)]
        public ServiceReference.CreateResponseBody Body;
        
        public CreateResponse()
        {
        }
        
        public CreateResponse(ServiceReference.CreateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateResponseBody
    {
        
        public CreateResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Edit", Namespace="http://webservices.example.com/GameServices/Game1", Order=0)]
        public ServiceReference.EditRequestBody Body;
        
        public EditRequest()
        {
        }
        
        public EditRequest(ServiceReference.EditRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.example.com/GameServices/Game1")]
    public partial class EditRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<int> id;
        
        public EditRequestBody()
        {
        }
        
        public EditRequestBody(System.Nullable<int> id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditResponse", Namespace="http://webservices.example.com/GameServices/Game1", Order=0)]
        public ServiceReference.EditResponseBody Body;
        
        public EditResponse()
        {
        }
        
        public EditResponse(ServiceReference.EditResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.example.com/GameServices/Game1")]
    public partial class EditResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.Settlement EditResult;
        
        public EditResponseBody()
        {
        }
        
        public EditResponseBody(ServiceReference.Settlement EditResult)
        {
            this.EditResult = EditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostEditRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostEdit", Namespace="http://webservices.example.com/GameServices/Game1", Order=0)]
        public ServiceReference.PostEditRequestBody Body;
        
        public PostEditRequest()
        {
        }
        
        public PostEditRequest(ServiceReference.PostEditRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.example.com/GameServices/Game1")]
    public partial class PostEditRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.Settlement settlement;
        
        public PostEditRequestBody()
        {
        }
        
        public PostEditRequestBody(ServiceReference.Settlement settlement)
        {
            this.settlement = settlement;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostEditResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostEditResponse", Namespace="http://webservices.example.com/GameServices/Game1", Order=0)]
        public ServiceReference.PostEditResponseBody Body;
        
        public PostEditResponse()
        {
        }
        
        public PostEditResponse(ServiceReference.PostEditResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PostEditResponseBody
    {
        
        public PostEditResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://webservices.example.com/GameServices/Game1", Order=0)]
        public ServiceReference.DeleteRequestBody Body;
        
        public DeleteRequest()
        {
        }
        
        public DeleteRequest(ServiceReference.DeleteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.example.com/GameServices/Game1")]
    public partial class DeleteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<int> id;
        
        public DeleteRequestBody()
        {
        }
        
        public DeleteRequestBody(System.Nullable<int> id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://webservices.example.com/GameServices/Game1", Order=0)]
        public ServiceReference.DeleteResponseBody Body;
        
        public DeleteResponse()
        {
        }
        
        public DeleteResponse(ServiceReference.DeleteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.example.com/GameServices/Game1")]
    public partial class DeleteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.Settlement DeleteResult;
        
        public DeleteResponseBody()
        {
        }
        
        public DeleteResponseBody(ServiceReference.Settlement DeleteResult)
        {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistrictsListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistrictsList", Namespace="http://webservices.example.com/GameServices/Game1", Order=0)]
        public ServiceReference.GetDistrictsListRequestBody Body;
        
        public GetDistrictsListRequest()
        {
        }
        
        public GetDistrictsListRequest(ServiceReference.GetDistrictsListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDistrictsListRequestBody
    {
        
        public GetDistrictsListRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistrictsListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistrictsListResponse", Namespace="http://webservices.example.com/GameServices/Game1", Order=0)]
        public ServiceReference.GetDistrictsListResponseBody Body;
        
        public GetDistrictsListResponse()
        {
        }
        
        public GetDistrictsListResponse(ServiceReference.GetDistrictsListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.example.com/GameServices/Game1")]
    public partial class GetDistrictsListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReference.District> GetDistrictsListResult;
        
        public GetDistrictsListResponseBody()
        {
        }
        
        public GetDistrictsListResponseBody(System.Collections.Generic.List<ServiceReference.District> GetDistrictsListResult)
        {
            this.GetDistrictsListResult = GetDistrictsListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface WebServiceSoapChannel : ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ServiceReference.WebServiceSoap>, ServiceReference.WebServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), WebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.IndexAsyncResponse> ServiceReference.WebServiceSoap.IndexAsyncAsync(ServiceReference.IndexAsyncRequest request)
        {
            return base.Channel.IndexAsyncAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.IndexAsyncResponse> IndexAsyncAsync(System.Nullable<int> id, System.Nullable<int> districtId)
        {
            ServiceReference.IndexAsyncRequest inValue = new ServiceReference.IndexAsyncRequest();
            inValue.Body = new ServiceReference.IndexAsyncRequestBody();
            inValue.Body.id = id;
            inValue.Body.districtId = districtId;
            return ((ServiceReference.WebServiceSoap)(this)).IndexAsyncAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.SIndexResponse> ServiceReference.WebServiceSoap.SIndexAsync(ServiceReference.SIndexRequest request)
        {
            return base.Channel.SIndexAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.SIndexResponse> SIndexAsync()
        {
            ServiceReference.SIndexRequest inValue = new ServiceReference.SIndexRequest();
            inValue.Body = new ServiceReference.SIndexRequestBody();
            return ((ServiceReference.WebServiceSoap)(this)).SIndexAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.CreateResponse> ServiceReference.WebServiceSoap.CreateAsync(ServiceReference.CreateRequest request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.CreateResponse> CreateAsync(ServiceReference.Settlement settlement)
        {
            ServiceReference.CreateRequest inValue = new ServiceReference.CreateRequest();
            inValue.Body = new ServiceReference.CreateRequestBody();
            inValue.Body.settlement = settlement;
            return ((ServiceReference.WebServiceSoap)(this)).CreateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.EditResponse> ServiceReference.WebServiceSoap.EditAsync(ServiceReference.EditRequest request)
        {
            return base.Channel.EditAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.EditResponse> EditAsync(System.Nullable<int> id)
        {
            ServiceReference.EditRequest inValue = new ServiceReference.EditRequest();
            inValue.Body = new ServiceReference.EditRequestBody();
            inValue.Body.id = id;
            return ((ServiceReference.WebServiceSoap)(this)).EditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.PostEditResponse> ServiceReference.WebServiceSoap.PostEditAsync(ServiceReference.PostEditRequest request)
        {
            return base.Channel.PostEditAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.PostEditResponse> PostEditAsync(ServiceReference.Settlement settlement)
        {
            ServiceReference.PostEditRequest inValue = new ServiceReference.PostEditRequest();
            inValue.Body = new ServiceReference.PostEditRequestBody();
            inValue.Body.settlement = settlement;
            return ((ServiceReference.WebServiceSoap)(this)).PostEditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.DeleteResponse> ServiceReference.WebServiceSoap.DeleteAsync(ServiceReference.DeleteRequest request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.DeleteResponse> DeleteAsync(System.Nullable<int> id)
        {
            ServiceReference.DeleteRequest inValue = new ServiceReference.DeleteRequest();
            inValue.Body = new ServiceReference.DeleteRequestBody();
            inValue.Body.id = id;
            return ((ServiceReference.WebServiceSoap)(this)).DeleteAsync(inValue);
        }
        
        public System.Threading.Tasks.Task PostDeleteAsync(int id)
        {
            return base.Channel.PostDeleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetDistrictsListResponse> ServiceReference.WebServiceSoap.GetDistrictsListAsync(ServiceReference.GetDistrictsListRequest request)
        {
            return base.Channel.GetDistrictsListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetDistrictsListResponse> GetDistrictsListAsync()
        {
            ServiceReference.GetDistrictsListRequest inValue = new ServiceReference.GetDistrictsListRequest();
            inValue.Body = new ServiceReference.GetDistrictsListRequestBody();
            return ((ServiceReference.WebServiceSoap)(this)).GetDistrictsListAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:56030/WebService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:56030/WebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebServiceSoap,
            
            WebServiceSoap12,
        }
    }
}
